[package]
name = "hevc_parser"
version = "0.5.1"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.56.1"
license = "MIT"
description = "HEVC format parser, incomplete"
repository = "https://github.com/quietvoid/hevc_parser"

[dependencies]
nom = "7.1.1"
bitvec_helpers = "2.0.0"
anyhow = "1.0.66"

regex = { version = "1.6.0", optional = true }

[features]
hevc_io = ["regex"]
